### ISSUE TITLE
ChangeRoad Action

### ISSUE THREAD

**Issue by baumfalk** [baumfalk/TrafficMAS#1]
The ChangeRoad Action is not yet implemented. It should work as follows:

When applicable, an agent should estimate if it is better to change road (and thus also a new route). That is, it should check if it is beneficial to change its current route and adapt a new one. It should do so when it will soon be in a position to change a road, and after it made this decision, it should commit to it (unless new information arrives). 

In practice, I think it would be best to sent the new calculated route to SUMO immediately after this decision is made. Maybe we should also allow agents do both take the ChangeRoad action as well as another action (such as ChangeVelocity), since the ChangeRoadAction doesn't conflict with other actions directly.

**Comment by Maxic** [comment]
Agent has a `currentRouteEdges`, `Edge[]`. In case of a changeRoute `AgentAction`, a new route is generated with A\* and `currentRouteEdges` is updated and the new data is immediately sent to SUMO in a `SumoStringList`.

**Comment by baumfalk** [comment]
It works now, but must be improved later on. See for example #14. Also, we have to implement that this action will only be considered when appropriate.
