### ISSUE TITLE
Allow conditions on actions

### ISSUE THREAD

**Issue by baumfalk** [baumfalk/TrafficMAS#26]
Currently, every action is taken into account every deliberation step. That is not always needed. For example, when we there only is one lane, we don't need to think about ChangeLane. Maybe we can make this a general option for actions, by using the expression in #23. This is a more general version of #25 .

**Comment by Maxic** [comment]
This can now be filled in for every action individually with the Action.isRelevant() method, implemented in 2b8f9a50
